[platformio]
src_dir = main
default_envs = esp32s3

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
framework = espidf
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0

[env:esp32s3]
board = esp32-s3-devkitc-1

[env:esp32s2]
board = esp32-s2-saola-1
