/**
 * @file Version.h
 * @brief Version information for TMP1x2.
 *
 * This file is AUTO-GENERATED by scripts/generate_version.py from library.json.
 * DO NOT EDIT MANUALLY. Update version metadata via library.json or
 * scripts/generate_version.py bump/set commands.
 */

#pragma once

#include <stdint.h>

#ifndef TMP1X2_VERSION_STRING
#define TMP1X2_VERSION_STRING "1.0.0"
#endif

#ifndef TMP1X2_BUILD_DATE
#define TMP1X2_BUILD_DATE "unknown"
#endif

#ifndef TMP1X2_BUILD_TIME
#define TMP1X2_BUILD_TIME "unknown"
#endif

#ifndef TMP1X2_BUILD_TIMESTAMP
#define TMP1X2_BUILD_TIMESTAMP "unknown"
#endif

#ifndef TMP1X2_GIT_COMMIT
#define TMP1X2_GIT_COMMIT "unknown"
#endif

#ifndef TMP1X2_GIT_STATUS
#define TMP1X2_GIT_STATUS "unknown"
#endif

#ifndef TMP1X2_VERSION_FULL
#define TMP1X2_VERSION_FULL TMP1X2_VERSION_STRING " (" TMP1X2_GIT_COMMIT ", " TMP1X2_BUILD_TIMESTAMP ", " TMP1X2_GIT_STATUS ")"
#endif

namespace TMP1x2 {

/// @brief Major version (breaking changes).
static constexpr uint16_t VERSION_MAJOR = 1;

/// @brief Minor version (backward-compatible features).
static constexpr uint16_t VERSION_MINOR = 0;

/// @brief Patch version (backward-compatible fixes).
static constexpr uint16_t VERSION_PATCH = 0;

/// @brief Full semantic version string.
static constexpr const char* VERSION = TMP1X2_VERSION_STRING;

/// @brief Encoded version for numeric comparison: MAJOR*10000 + MINOR*100 + PATCH.
static constexpr uint32_t VERSION_CODE = 10000;

/// @brief Backward-compatible alias used by older repositories.
static constexpr int VERSION_INT = 10000;

/// @brief Build date string.
static constexpr const char* BUILD_DATE = TMP1X2_BUILD_DATE;

/// @brief Build time string.
static constexpr const char* BUILD_TIME = TMP1X2_BUILD_TIME;

/// @brief Build timestamp string.
static constexpr const char* BUILD_TIMESTAMP = TMP1X2_BUILD_TIMESTAMP;

/// @brief Git commit string.
static constexpr const char* GIT_COMMIT = TMP1X2_GIT_COMMIT;

/// @brief Git working tree status string.
static constexpr const char* GIT_STATUS = TMP1X2_GIT_STATUS;

/// @brief Full version string with build metadata.
static constexpr const char* VERSION_FULL = TMP1X2_VERSION_FULL;

}  // namespace TMP1x2
